### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by susilehtola** [MRChemSoft/mrchem#389]
I'm trying to package MRChem in Fedora. Unfortunately, I'm experiencing random crashes that don't even produce reasonable core dumps. Any guidance on how to debug this?

**Comment by stigrj** [comment]
We have had some issues with other packaging options like Conda, which I think was related to hardware optimizations (`-xHost`, `-march=native`) etc. Try to build with `--arch-flags=False` in the CMake `setup`.

@robertodr do you remember any details from the Conda issues?

**Comment by susilehtola** [comment]
Yeah well native hardware optimizations aren't even allowed on Fedora so setting `-DENABLE_ARCH_FLAGS=OFF` was one of the first things I did ;)

**Comment by susilehtola** [comment]
After a bit of trial and error to get the problem size small enough that the core dump doesn't get truncated, this is what I get
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f8cb100d8b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f8cb0fc06a6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f8cb0faa7d3 in __GI_abort () at abort.c:79
#4  0x00007f8cb16e9be8 in std::__replacement_assert (__file=<optimized out>, __line=<optimized out>, __function=<optimized out>, __condition=<optimized out>)
    at /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h:2660
#5  0x00007f8cb17724e8 in std::vector<int, std::allocator<int> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/11/bits/stl_vector.h:1061
#6  std::vector<int, std::allocator<int> >::operator[] (__n=<optimized out>, this=0x55ae699f4608) at /usr/include/c++/11/bits/stl_vector.h:1061
#7  mrcpp::NodeAllocator<3>::findNextOccupied (this=this@entry=0x55ae699f45f0, sIdx=<optimized out>, sIdx@entry=552)
    at /usr/src/debug/mrcpp-1.4.0-2.fc35.x86_64/src/trees/NodeAllocator.cpp:344
#8  0x00007f8cb17743c2 in mrcpp::NodeAllocator<3>::compress (this=0x55ae699f45f0) at /usr/src/debug/mrcpp-1.4.0-2.fc35.x86_64/src/trees/NodeAllocator.cpp:224
#9  0x00007f8cb175501b in mrcpp::FunctionTree<3>::crop (this=0x55ae64f74680, prec=prec@entry=0.00032258064516129032, splitFac=splitFac@entry=1, absPrec=absPrec@entry=false)
    at /usr/include/c++/11/bits/unique_ptr.h:407
#10 0x000055ae5d2b98dd in mrchem::QMFunction::crop (this=0x7fff24234700, prec=0.00032258064516129032) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmfunctions/QMFunction.cpp:127
#11 0x000055ae5d2c5610 in mrchem::density::compute_local (prec=0.01, rho=..., Phi=..., spin=DensityType::Beta)
    at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmfunctions/density_utils.cpp:158
#12 0x000055ae5d2c5bb6 in mrchem::density::compute (prec=0.01, rho=..., Phi=std::vector of length 31, capacity 32 = {...}, spin=DensityType::Beta)
    at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmfunctions/density_utils.cpp:112
#13 0x000055ae5d2d4db2 in mrchem::XCPotentialD1::setupDensities (this=0x55ae5ea7b5c0, prec=0.01, grid=...) at /usr/include/c++/11/bits/shared_ptr_base.h:979
#14 0x000055ae5d2d2983 in mrchem::XCPotential::setup (this=0x55ae5ea7b5c0, prec=<optimized out>) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmoperators/two_electron/XCPotential.cpp:36
#15 0x000055ae5d2caf7a in mrchem::RankZeroTensorOperator::setup (this=<optimized out>, prec=0.01) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmoperators/RankZeroTensorOperator.cpp:153
#16 0x000055ae5d2d4123 in mrchem::FockOperator::setup (this=0x7fff24236340, prec=0.01) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/qmoperators/two_electron/FockOperator.cpp:88
#17 0x000055ae5d3096ed in mrchem::GroundStateSolver::optimize[abi:cxx11](mrchem::Molecule&, mrchem::FockOperator&) [clone .constprop.0] (this=this@entry=0x7fff242367a0, mol=..., F=...)
    at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/scf_solver/GroundStateSolver.cpp:293
#18 0x000055ae5d28980b in mrchem::driver::scf::run (json_scf=..., mol=...) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/driver.cpp:256
#19 0x000055ae5d2754fc in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mrchem-1.0.2-1.fc35.x86_64/src/mrchem.cpp:62
```

**Comment by stigrj** [comment]
Was this issue fully resolved by your MRCPP fix?

**Comment by susilehtola** [comment]
Yes, they were.
