### ISSUE TITLE
Translate molecule failing

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#410]
The input parser is failing on me in the new `validator` module when I try to `translate = true` a molecule to CoM:
```
Traceback (most recent call last):
  File "../install-master/bin/mrchem", line 105, in <module>
    main()
  File "../install-master/bin/mrchem", line 85, in main
    program_dict = {"input": translate_input(user_dict)}
  File "/home/stig/src/mrchem/install-master/lib/python/mrchem/api.py", line 49, in translate_input
    mol_dict = write_molecule(user_dict, origin)
  File "/home/stig/src/mrchem/install-master/lib/python/mrchem/api.py", line 124, in write_molecule
    mol = MoleculeValidator(user_dict, origin)
  File "/home/stig/src/mrchem/install-master/lib/python/mrchem/validators.py", line 116, in __init__
    self.atomic_coords = self.translate_com_to_origin()
  File "/home/stig/src/mrchem/install-master/lib/python/mrchem/validators.py", line 318, in translate_com_to_origin
    return [masses[i] * (self.atomic_coords[i] - self.origin[i]) / M for i in range(3)]
  File "/home/stig/src/mrchem/install-master/lib/python/mrchem/validators.py", line 318, in <listcomp>
    return [masses[i] * (self.atomic_coords[i] - self.origin[i]) / M for i in range(3)]
TypeError: unsupported operand type(s) for -: 'list' and 'float'
```

**Comment by Andersmb** [comment]
on it...
